name: Usage
on:
  issue_comment:
    types: [created]

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: "A cute baby sea otter"
      - run: gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments -f body="![image](${{ steps.run.outputs.image }})"
        env:
          GH_TOKEN: ${{ github.token }}